/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mymancala;

/**
 *
 * @author zak
 */

import javax.swing.JButton;
public class MancalaGUI extends javax.swing.JFrame {

    /**
     * Creates new form MancalaGUI
     */
    JButton buttons[][];
    MancalaGame mancalaGame;
    public MancalaGUI(MancalaGame game) {
        buttons=new JButton[2][7];
        mancalaGame=game;
        initComponents();
        buttons[0][0] = HumanButton1 ;
        buttons[0][1] = HumanButton2; 
        buttons[0][2] = HumanButton3 ;
        buttons[0][3] = HumanButton4 ;
        buttons[0][4] = HumanButton5 ;
        buttons[0][5] = HumanButton6 ;
        buttons[0][6] = HumanMancalaButton ;
        
               
        buttons[1][0] = AIButton1 ;
        buttons[1][1] = AIButton2 ;
        buttons[1][2] = AIButton3 ;
        buttons[1][3]= AIButton4 ;
        buttons[1][4]= AIButton5 ;
        buttons[1][5]= AIButton6 ;
        
        buttons[1][6]= AIMancalaButton ;
        
        setBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HumanButton1 = new javax.swing.JButton();
        HumanButton2 = new javax.swing.JButton();
        HumanButton3 = new javax.swing.JButton();
        HumanButton4 = new javax.swing.JButton();
        HumanButton5 = new javax.swing.JButton();
        HumanButton6 = new javax.swing.JButton();
        AIButton1 = new javax.swing.JButton();
        AIButton2 = new javax.swing.JButton();
        AIButton3 = new javax.swing.JButton();
        AIButton4 = new javax.swing.JButton();
        AIButton5 = new javax.swing.JButton();
        AIButton6 = new javax.swing.JButton();
        HumanMancalaButton = new javax.swing.JButton();
        AIMancalaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HumanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanButton1ActionPerformed(evt);
            }
        });

        HumanButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanButton2ActionPerformed(evt);
            }
        });

        HumanButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanButton3ActionPerformed(evt);
            }
        });

        HumanButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanButton4ActionPerformed(evt);
            }
        });

        HumanButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanButton5ActionPerformed(evt);
            }
        });

        HumanButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanButton6ActionPerformed(evt);
            }
        });

        AIButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIButton1ActionPerformed(evt);
            }
        });

        AIButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIButton2ActionPerformed(evt);
            }
        });

        AIButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIButton3ActionPerformed(evt);
            }
        });

        AIButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIButton4ActionPerformed(evt);
            }
        });

        AIButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIButton5ActionPerformed(evt);
            }
        });

        AIButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIButton6ActionPerformed(evt);
            }
        });

        HumanMancalaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanMancalaButtonActionPerformed(evt);
            }
        });

        AIMancalaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIMancalaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HumanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HumanButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HumanButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HumanButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HumanButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HumanButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AIButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AIButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AIMancalaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AIButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AIButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HumanMancalaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AIButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AIButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AIButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AIButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AIButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AIButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AIButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HumanMancalaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AIMancalaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AIButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HumanButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HumanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanButton1ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="0";
        mancalaGame.isButtonPressed=true;
        System.out.println("OUCH");
        //setBoard();
    }//GEN-LAST:event_HumanButton1ActionPerformed

    private void HumanButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanButton2ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="1";
        mancalaGame.isButtonPressed=true;
        
        setBoard();
   
    }//GEN-LAST:event_HumanButton2ActionPerformed

    private void HumanButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanButton3ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="2";
        mancalaGame.isButtonPressed=true;
        
    //    setBoard();
   
    }//GEN-LAST:event_HumanButton3ActionPerformed

    private void HumanButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanButton4ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="3";
        mancalaGame.isButtonPressed=true;
        
      //  setBoard();
   
    }//GEN-LAST:event_HumanButton4ActionPerformed

    private void HumanButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanButton5ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="4";
        mancalaGame.isButtonPressed=true;
        
        //setBoard();
   
    }//GEN-LAST:event_HumanButton5ActionPerformed

    private void HumanButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanButton6ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="5";
        mancalaGame.isButtonPressed=true;
        
        //setBoard();
   
    }//GEN-LAST:event_HumanButton6ActionPerformed

    private void AIButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIButton1ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="10";
        mancalaGame.isButtonPressed=true;
        
       // setBoard();
    }//GEN-LAST:event_AIButton1ActionPerformed

    private void AIButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIButton2ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="11";
        mancalaGame.isButtonPressed=true;
        
        //setBoard();
    
    }//GEN-LAST:event_AIButton2ActionPerformed

    private void AIButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIButton3ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="12";
        mancalaGame.isButtonPressed=true;
        
        //setBoard();
    
    }//GEN-LAST:event_AIButton3ActionPerformed

    private void AIButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIButton4ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="13";
        mancalaGame.isButtonPressed=true;
        
       // setBoard();
    
    }//GEN-LAST:event_AIButton4ActionPerformed

    private void AIButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIButton5ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="14";
        mancalaGame.isButtonPressed=true;
        
        //setBoard();
    
    }//GEN-LAST:event_AIButton5ActionPerformed

    private void AIButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIButton6ActionPerformed
        // TODO add your handling code here:
        mancalaGame.whichButtonPressed="15";
        mancalaGame.isButtonPressed=true;
        
        //setBoard();
    
    }//GEN-LAST:event_AIButton6ActionPerformed

    private void HumanMancalaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanMancalaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HumanMancalaButtonActionPerformed

    private void AIMancalaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIMancalaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AIMancalaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               // new MancalaGUI().setVisible(true);
            }
        });
    }
    
    public  void runMancalaGUI()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MancalaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MancalaGUI.this.setVisible(true);
            }
        });
    
    
    }
    
    public void setBoard()
    {
        
    for(int i=0;i<7;i++)
        {
        buttons[0][i].setText(Integer.toString(mancalaGame.boardConfig[0][i]));
        
        for(int j=0;j<2000000;j++)
            ;
        }
    for(int i=0;i<7;i++)
        {
        buttons[1][i].setText(Integer.toString(mancalaGame.boardConfig[1][i]));
        for(int j=0;j<2000000;j++)
            ;
        
               
            
        }

    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AIButton1;
    private javax.swing.JButton AIButton2;
    private javax.swing.JButton AIButton3;
    private javax.swing.JButton AIButton4;
    private javax.swing.JButton AIButton5;
    private javax.swing.JButton AIButton6;
    private javax.swing.JButton AIMancalaButton;
    private javax.swing.JButton HumanButton1;
    private javax.swing.JButton HumanButton2;
    private javax.swing.JButton HumanButton3;
    private javax.swing.JButton HumanButton4;
    private javax.swing.JButton HumanButton5;
    private javax.swing.JButton HumanButton6;
    private javax.swing.JButton HumanMancalaButton;
    // End of variables declaration//GEN-END:variables
}
